// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabKz0BqKqkttz8ZaNVBLdyhH0sJADQk4',
    appId: '1:215565652261:web:cc376d37631390d7268acc',
    messagingSenderId: '215565652261',
    projectId: 'hydroponic-908ac',
    authDomain: 'hydroponic-908ac.firebaseapp.com',
    storageBucket: 'hydroponic-908ac.appspot.com',
    measurementId: 'G-W3NTXNKZZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhUrCAyfXOa_5WKeS0w-sd58d5FJftjoQ',
    appId: '1:215565652261:android:a673795b32dc949a268acc',
    messagingSenderId: '215565652261',
    projectId: 'hydroponic-908ac',
    storageBucket: 'hydroponic-908ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfqE5U2IgBLY756FuLEN_54SxrQ8C5b8k',
    appId: '1:215565652261:ios:06fd8d41994cee80268acc',
    messagingSenderId: '215565652261',
    projectId: 'hydroponic-908ac',
    storageBucket: 'hydroponic-908ac.appspot.com',
    androidClientId: '215565652261-v0fglnjs9d3pch67nfb8pkg8m3f6h7kn.apps.googleusercontent.com',
    iosClientId: '215565652261-drii75kd4be90pbd5vqjghiek07dv5v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrophonic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfqE5U2IgBLY756FuLEN_54SxrQ8C5b8k',
    appId: '1:215565652261:ios:06fd8d41994cee80268acc',
    messagingSenderId: '215565652261',
    projectId: 'hydroponic-908ac',
    storageBucket: 'hydroponic-908ac.appspot.com',
    androidClientId: '215565652261-v0fglnjs9d3pch67nfb8pkg8m3f6h7kn.apps.googleusercontent.com',
    iosClientId: '215565652261-drii75kd4be90pbd5vqjghiek07dv5v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydrophonic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabKz0BqKqkttz8ZaNVBLdyhH0sJADQk4',
    appId: '1:215565652261:web:6d6ec00ee283afa7268acc',
    messagingSenderId: '215565652261',
    projectId: 'hydroponic-908ac',
    authDomain: 'hydroponic-908ac.firebaseapp.com',
    storageBucket: 'hydroponic-908ac.appspot.com',
    measurementId: 'G-KKY41S0YP0',
  );
}
